---
- name: copy nginx.conf to lb 
  template: 
    src: nginx.conf.j2
    dest: /etc/nginx.conf
    owner: root
    group: root
    mode: '0644' 

- name: docker py 
  pip: 
    name: docker-py

- name: start nginx container
  docker_container: 
    name: rancherlb 
    image: nginx:1.14
    state: started
    restart: yes 
    exposed_ports: 
      - 80
      - 443 
    volumes: 
      - /etc/nginx.conf:/etc/nginx/nginx.conf
