---
- hosts: all 
  become: true
  roles: 
    - common 

- hosts: kubernetes-master-nodes 
  become: true
  roles: 
    - master 

- hosts: kubernetes-worker-nodes
  become: true
  roles: 
    - worker
