---
- name: install rke 
  get_url:
    url: https://github.com/rancher/rke/releases/download/v1.0.4/rke_linux-amd64 
    dest: /usr/local/bin/rke_linux-amd64
    mode: '0644'
  become: true

- name: install helm 
  get_url: 
    url: https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
    dest: /usr/local/bin/helm-v3.1.1-linux-amd64.tar.gz
    mode: '0644'
  become: true

- name: unpack helm 
  shell: "cd /usr/local/bin && tar xfvz helm-v3.1.1-linux-amd64.tar.gz && mv linux-amd64/helm helm"
  become: true

- name: rename rke  
  shell: "cd /usr/local/bin && mv rke_linux* rke && chmod +x rke" 
  become: true

- name: add helm stable repo 
  command: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

- name: install helm rancher
  command: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest

- name: update helm repos 
  command: helm repo update

- name: prep kubectl for hal9000
  file: 
    path: /home/hal9000/.kube 
    mode: '0750'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: true
 
- name: prep kubectl for root
  file:
    path: /root/.kube
    mode: '0750'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
  become: true

- name: copy cluster template 
  template: 
    src: cluster.yml.j2
    dest: /tmp/cluster.yml 
  become: true

- name: execute rke
  command: rke up --config /tmp/cluster.yml

- name: deploy config 
  shell: "cp /tmp/kube_config_cluster.yml /home/hal9000/.kube/config && cp /tmp/kube_config_cluster.yml /root/.kube/config "
  become: true

- name: change ownership 
  file: 
    path: /home/hal9000/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'
  become: true


