---
- name: cleanup kubernetes data
  shell: |
   kubeadm reset -f
   systemctl stop kubelet
   systemctl stop docker
   rm -rf /var/lib/cni/
   rm -rf /var/lib/etcd
   rm -rf /var/lib/kubelet/*
   rm -rf /etc/nginx.conf
   rm -rf /etc/cni/
   ip link delete cni0
   rm -rf /var/lib/docker/*
   rm -rf /etc/kubernetes

#- name: Prune everything (including non-dangling images)
#  docker_prune:
#    containers: yes
#    images: yes
#    images_filters:
#      dangling: false
#    networks: yes
#    volumes: yes
#    builder_cache: yes

- name: remove dirs
  file: 
   path: "{{item}}" 
   state: absent
  loop: 
   - /etc/kubernetes
   - /home/hal9000/.kube


- name: Remove docker-ce-stable repo
  yum_repository:
   name: docker-ce
   state: absent

- name: Remove kubernetes repo
  yum_repository:
   name: kubernetes
   state: absent

