---
- name: install rke 
  get_url:
    url: https://github.com/rancher/rke/releases/download/v1.0.4/rke_linux-amd64 
    dest: /usr/local/bin/rke_linux-amd64
    mode: '0640'
  become: true

- name: install helm 
  get_url: 
    url: https://get.helm.sh/helm-v3.1.1-linux-amd64.tar.gz
    dest: /usr/local/bin/helm-v3.1.1-linux-amd64.tar.gz
    mode: '0640'
  become: true

- name: rename rke and unpack helm 
  shell: "cd /usr/local/bin && mv rke_linux* rke && chmod +x rke && tar xfvz helm-v3.1.1-linux-amd64.tar.gz && mv linux-amd64/helm helm"


- name: add helm stable repo 
  command: helm repo add stable https://kubernetes-charts.storage.googleapis.com/

- name: install helm rancher
  command: helm repo add rancher-latest https://releases.rancher.com/server-charts/latest

- name: update helm repos 
  command: helm repo update

- name: prep kubectl 
  file: 
    path: "{{ item }}" 
    mode: '0755'
    state: directory
  loop: 
    - /home/hal9000/.kube
    - /root/.kube

- name: copy cluster template 
  template: 
    src: cluster.yml.j2
    dest: /tmp/cluster.yml 
    state: present 

- name: execute rke
  shell: "cd /tmp && rke up && cp kube_config_cluster.yml /home/{{ ansible_user }}/.kube/config &&  mv kube_config_cluster.yml /root/.kube/config"
