ad_addr: 192.168.178.51 
cidr_v: 172.16.0.0/16
ansible_user: hal9000
network_zone: public 

cluster_version: v1.17.4-rancher1 
#cluster_version: v1.17.2-rancher1-2
cluster_name: rancherlb

rke_bin: https://github.com/rancher/rke/releases/download/v1.0.14/rke_linux-amd64
helm_bin: https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz

packages:
- kubeadm
- kubectl
- ansible 
- htop 
- nload 
- git 
- python-pip
- wget 
- qemu-guest-agent

docker_images: 
  - rancher/coreos-etcd:v3.4.3-rancher1
  - rancher/rke-tools:v0.1.66
  - rancher/k8s-dns-kube-dns:1.15.0
  - rancher/k8s-dns-dnsmasq-nanny:1.15.0
  - rancher/k8s-dns-sidecar:1.15.0
  - rancher/cluster-proportional-autoscaler:1.7.1
  - rancher/coredns-coredns:1.6.5
  - rancher/k8s-dns-node-cache:1.15.7
  - rancher/hyperkube:v1.17.14-rancher1
  - rancher/coreos-flannel:v0.12.0
  - rancher/flannel-cni:v0.3.0-rancher6
  - rancher/calico-node:v3.13.4
  - rancher/calico-cni:v3.13.4
  - rancher/calico-kube-controllers:v3.13.4
  - rancher/calico-ctl:v3.13.4
  - rancher/calico-pod2daemon-flexvol:v3.13.4
  - weaveworks/weave-kube:2.6.4
  - weaveworks/weave-npc:2.6.4
  - rancher/pause:3.1
  - rancher/nginx-ingress-controller:nginx-0.35.0-rancher2
  - rancher/nginx-ingress-controller-defaultbackend:1.5-rancher1
  - rancher/metrics-server:v0.3.6

sys_ports: 
 - 6443/tcp
 - 5443/tcp
 - 2379-2380/tcp
 - 10250/tcp
 - 10251/tcp
 - 10252/tcp
 - 10053/tcp
 - 10053/udp
 - 10255/tcp
 - 30000-32767/tcp
 - 8082/tcp
 - 8472/udp
 - 8285/udp
 - 9898/tcp
 - 9100/tcp
 - 443/tcp
 - 53/tcp
 - 53/udp
 - 80/tcp
 - 443/tcp
 - 4194/tcp
 - 10254/tcp

pip_modules:
 - pip 
 - docker


kernel_modules:
      - br_netfilter
      - ip6_udp_tunnel
      - ip_set
      - ip_set_hash_ip
      - ip_set_hash_net
      - iptable_filter
      - iptable_nat
      - iptable_mangle
      - iptable_raw
      - nf_conntrack_netlink
      - nf_conntrack
      - nf_conntrack_ipv4
      - nf_defrag_ipv4
      - nf_nat
      - nf_nat_ipv4
      - nf_nat_masquerade_ipv4
      - nfnetlink
      - udp_tunnel
      - veth
      - vxlan
      - x_tables
      - xt_addrtype
      - xt_conntrack
      - xt_comment
      - xt_mark
      - xt_multiport
      - xt_nat
      - xt_recent
      - xt_set
      - xt_statistic
      - xt_tcpudp


services:
- docker
- kubelet
- firewalld

ports:
- "6443/tcp"
- "10250/tcp"

token_file: join_token

